export enum Collections {
  Channels = 'channels',
  Chats = 'chats',
  Conversations = 'conversations',
  Friends = 'friends',
  GroupConversations = 'group_conversations',
  Groups = 'groups',
  MemberOf = 'member_of',
  Members = 'members',
  Messages = 'messages',
  MyFriends = 'myfriends',
  Notifications = 'notifications',
  Requests = 'requests',
  Status = 'status',
  Users = 'users',
}
